VITE_SUPABASE_URL=https://qtgfhipgzizridykdplr.supabase.co
VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0Z2ZoaXBneml6cmlkeWtkcGxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5NDI0MjgsImV4cCI6MjA4MzUxODQyOH0.aJpnB-B7puQOUvcBOisrNuotZjlx_5tGmiTgZ4m4zU4
