export interface WasteClass {
  id: string;
  name: string;
  description: string;
  subtypes: string[];
}

export const WASTE_CLASSES: WasteClass[] = [
  { id: 'C1', name: 'MUNICIPAL SOLID WASTE (MSW)', description: 'Everyday waste from households & urban environments', subtypes: ['Food waste', 'Paper & cardboard', 'Plastics', 'Glass', 'Metals', 'Textiles', 'Leather', 'Rubber', 'Yard/garden waste', 'Household packaging'] },
  { id: 'C2', name: 'CONSTRUCTION & DEMOLITION (C&D) WASTE', description: 'Critical structural materials and debris', subtypes: ['Concrete', 'Bricks', 'Tiles', 'Asphalt', 'Stone', 'Timber', 'Plywood', 'Steel', 'Aluminum', 'Copper wiring', 'PVC pipes', 'Insulation foam', 'Asbestos', 'Lead-based paint', 'Contaminated soil', 'Composite materials', 'Multi-layer construction debris'] },
  { id: 'C3', name: 'INDUSTRIAL WASTE', description: 'Generated by manufacturing & processing industries', subtypes: ['Process waste', 'Chemical waste', 'Slag', 'Fly ash', 'Industrial sludge', 'Scrap materials'] },
  { id: 'C4', name: 'HAZARDOUS WASTE', description: 'Dangerous to human health or environment', subtypes: ['Solvents', 'Acids', 'Alkalis', 'Pesticides', 'Heavy metals', 'Cyanide waste', 'Infectious materials', 'Contaminated sharps', 'Asbestos', 'Contaminated concrete'] },
  { id: 'C5', name: 'ELECTRONIC WASTE (E-WASTE)', description: 'Discarded electronic appliances and devices', subtypes: ['Computers & laptops', 'Mobile phones', 'TVs & monitors', 'Batteries', 'Circuit boards', 'Electrical cables'] },
  { id: 'C6', name: 'ORGANIC / BIODEGRADABLE WASTE', description: 'Waste capable of undergoing anaerobic or aerobic decomposition', subtypes: ['Food waste', 'Agricultural waste', 'Animal waste', 'Green waste', 'Wood waste'] },
  { id: 'C7', name: 'RECYCLABLE WASTE', description: 'Materials that can be reprocessed', subtypes: ['Paper', 'Plastics', 'Glass', 'Metals', 'Textiles'] },
  { id: 'C8', name: 'NON-RECYCLABLE WASTE', description: 'Materials difficult or impossible to recycle', subtypes: ['Contaminated plastics', 'Multi-layer packaging', 'Composite materials', 'Ceramics'] },
  { id: 'C9', name: 'INERT WASTE', description: 'Does not decompose or react chemically', subtypes: ['Sand', 'Soil', 'Concrete rubble', 'Gravel', 'Bricks'] },
  { id: 'C10', name: 'LIQUID WASTE', description: 'Fluid waste materials', subtypes: ['Wastewater', 'Industrial effluents', 'Oil waste', 'Chemical liquids', 'Sewage'] },
  { id: 'C11', name: 'GASEOUS WASTE', description: 'Gaseous emissions', subtypes: ['Carbon dioxide (CO2)', 'Methane (CH4)', 'Nitrogen oxides (NOx)', 'Sulfur dioxide (SO2)', 'Industrial emissions'] },
  { id: 'C12', name: 'MEDICAL / HEALTHCARE WASTE', description: 'Waste from medical procedures and treatments', subtypes: ['Infectious waste', 'Pathological waste', 'Sharps', 'Pharmaceutical waste', 'Radioactive medical waste'] },
  { id: 'C13', name: 'AGRICULTURAL WASTE', description: 'Waste produced as a result of various agricultural operations', subtypes: ['Crop residues', 'Animal manure', 'Pesticide containers', 'Irrigation waste'] },
  { id: 'C14', name: 'MINING & EXTRACTIVE WASTE', description: 'Waste generated during the extraction of minerals', subtypes: ['Tailings', 'Overburden', 'Waste rock', 'Sludge'] },
  { id: 'C15', name: 'RADIOACTIVE WASTE', description: 'Waste containing radioactive material', subtypes: ['Low-level waste', 'Intermediate-level waste', 'High-level waste'] },
  { id: 'C16', name: 'PACKAGING WASTE', description: 'Discarded packaging materials', subtypes: ['Plastic packaging', 'Paper packaging', 'Glass bottles', 'Metal cans', 'Composite packaging'] },
  { id: 'C17', name: 'SPECIAL / BULKY WASTE', description: 'Large scale municipal or commercial waste', subtypes: ['Furniture', 'Mattresses', 'Appliances', 'Construction equipment waste'] },
  { id: 'C18', name: 'DIGITAL / DATA WASTE', description: 'Hardware and energy waste from digital infrastructure', subtypes: ['Data storage waste', 'Cloud redundancy', 'Server energy waste'] },
  { id: 'C19', name: 'DEMOLITION-SPECIFIC WASTE STREAMS', description: 'Waste purely designated to tearing down structures', subtypes: ['Structural debris', 'Finishing materials', 'Mechanical systems', 'Electrical systems'] }
];

export interface WasteDataStructure {
  Waste_ID: string;
  Category: string; // From WasteClass
  Type: string;
  Sub_Type: string;
  Hazard_Level: 'Low' | 'Medium' | 'High' | 'Critical';
  Recyclability_Score: 'High' | 'Medium' | 'Low / Difficult';
  Quantity: number;
  Carbon_Impact: number; // Est in kgC02e
  Reuse_Potential: 'High' | 'Medium' | 'Low';
  Disposal_Option: string; // e.g. "Recycle as aggregate"
}
